### ISSUE TITLE
Cannot read property 'position' of undefined 

### ISSUE THREAD

**Issue by OurMajesty** [fpdrozd/OverlayScrollbarsChat#1]
Looks like there's wrong properties order:
https://github.com/fpdrozd/OverlayScrollbarsChat/blob/8541e53443b9b2730d6abf12b5486cfdbb499508/src/scrollBehavior.js#L3
According to documentation, `scroll()` method returns structure with `position: { x, y }`

**Comment by krowst** [comment]
>> const position = scrollbar.scroll().y.position; 

Yes, this line isn't working for me too..
